### PR TITLE
Updated dependency to Apache.NMS.ActiveMQ ver. 2.1.0

### PR DESCRIPTION
**Pull request by snakefoot**
Preview README.md: https://github.com/snakefoot/NLog.Targets.ActiveMQ/blob/master/README.md

### CODE REVIEW

**Comment by snakefoot** [comment]
@YuraSidorets Ready for review

**Review by YuraSidorets — APPROVED** [review]

**Comment by snakefoot** [comment]
Thank you for the fast review + merge + release. Looks great

**Comment by YuraSidorets** [comment]
@snakefoot Thank you for your contribution. Appreciate it

**Comment by snakefoot** [comment]
Added the nuget-package to the official target-list: https://nlog-project.org/config/?tab=targets

**Pull request merged**
